name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        
        

    steps:
      - uses: actions/checkout@v3
      
      

      

      - name: Run tests
        run: |
          
          